# Generated by Django 4.2.1 on 2023-07-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='template',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='workout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
