# Generated by Django 4.2.1 on 2023-07-18 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqauts', models.IntegerField()),
                ('lunges', models.IntegerField()),
                ('dead_lifts', models.IntegerField()),
                ('shoulder_press', models.IntegerField()),
                ('bicep_curls', models.IntegerField()),
                ('tricep_kickbacks', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
